// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Miro Eilola / Mironet
#include "texts.h"

const char *const texts_en[TXT_COUNT] = {
    [TXT_DASHBOARD]     = "Ventilation",
    [TXT_MENU]          = "Menu",
    [TXT_FAN_SPEED]     = "Fan speed",
    [TXT_HEAT_SETPOINT] = "Heating setpoint",
    [TXT_STATUS]        = "Status",
    [TXT_SETTINGS]      = "Settings",
    [TXT_LANGUAGE]      = "Language",
    [TXT_ENGLISH]       = "English",
    [TXT_FINNISH]       = "Suomi",
    [TXT_OUTDOOR]       = "Outdoor",
    [TXT_SUPPLY]        = "Supply",
    [TXT_EXTRACT]       = "Extract",
    [TXT_EXHAUST]       = "Exhaust",
    [TXT_HEATER_ON]     = "Heating",
    [TXT_BYPASS]        = "Bypass",
    [TXT_BOOST_MIN]     = "Boost %d min",
    [TXT_NO_BUS]        = "No bus",
    [TXT_FAULT]         = "Fault",
    [TXT_NO_FAULT]      = "No fault",
    [TXT_SERVICE_IN]    = "Service in %d months",
    [TXT_SERVICE_NOW]   = "Service due",
    [TXT_READ_ONLY]     = "Read-only until verified",
    [TXT_FACTORY_RESET] = "Factory reset",
    [TXT_FIRMWARE]      = "Firmware",
    [TXT_BUS]           = "Bus",
    [TXT_OK_WORD]       = "OK",
    [TXT_BTN_MINUS]     = "-",
    [TXT_BTN_PLUS]      = "+",
    [TXT_BTN_OK]        = "OK",
    [TXT_BTN_BACK]      = "<",
    [TXT_BTN_SAVE]      = "Save",
    [TXT_BTN_BACK_WORD] = "Back",
    [TXT_BTN_UP]        = "Up",
    [TXT_BTN_DOWN]      = "Down",
    [TXT_UNIT_C]        = "°C",
    [TXT_STALE]         = "--",
    [TXT_SPEED_OF]      = "of 8",
    [TXT_FAULT_SUPPLY_SENSOR]    = "Supply air sensor",
    [TXT_FAULT_CO2_ALARM]        = "CO2 alarm",
    [TXT_FAULT_OUTDOOR_SENSOR]   = "Outdoor air sensor",
    [TXT_FAULT_EXTRACT_SENSOR]   = "Extract air sensor",
    [TXT_FAULT_WATER_COIL_FROST] = "Water coil frost risk",
    [TXT_FAULT_EXHAUST_SENSOR]   = "Exhaust air sensor",
    [TXT_FAULT_UNKNOWN]          = "Code %d",
};
