// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Miro Eilola / Mironet
#include "texts.h"

const char *const texts_fi[TXT_COUNT] = {
    [TXT_DASHBOARD]     = "Ilmanvaihto",
    [TXT_MENU]          = "Valikko",
    [TXT_FAN_SPEED]     = "Puhallinnopeus",
    [TXT_HEAT_SETPOINT] = "Lämmityksen asetus",
    [TXT_STATUS]        = "Tila",
    [TXT_SETTINGS]      = "Asetukset",
    [TXT_LANGUAGE]      = "Kieli",
    [TXT_ENGLISH]       = "English",
    [TXT_FINNISH]       = "Suomi",
    [TXT_OUTDOOR]       = "Ulko",
    [TXT_SUPPLY]        = "Tulo",
    [TXT_EXTRACT]       = "Poisto",
    [TXT_EXHAUST]       = "Jäte",
    [TXT_HEATER_ON]     = "Lämmitys",
    [TXT_BYPASS]        = "Ohitus",
    [TXT_BOOST_MIN]     = "Tehostus %d min",
    [TXT_NO_BUS]        = "Ei väylää",
    [TXT_FAULT]         = "Vika",
    [TXT_NO_FAULT]      = "Ei vikaa",
    [TXT_SERVICE_IN]    = "Huolto %d kk kuluttua",
    [TXT_SERVICE_NOW]   = "Huolto nyt",
    [TXT_READ_ONLY]     = "Vain luku kunnes todennettu",
    [TXT_FACTORY_RESET] = "Tehdasasetukset",
    [TXT_FIRMWARE]      = "Laiteohjelmisto",
    [TXT_BUS]           = "Väylä",
    [TXT_OK_WORD]       = "OK",
    [TXT_BTN_MINUS]     = "-",
    [TXT_BTN_PLUS]      = "+",
    [TXT_BTN_OK]        = "OK",
    [TXT_BTN_BACK]      = "<",
    [TXT_BTN_SAVE]      = "Tallenna",
    [TXT_BTN_BACK_WORD] = "Takaisin",
    [TXT_BTN_UP]        = "Ylös",
    [TXT_BTN_DOWN]      = "Alas",
    [TXT_UNIT_C]        = "°C",
    [TXT_STALE]         = "--",
    [TXT_SPEED_OF]      = "/ 8",
    [TXT_FAULT_SUPPLY_SENSOR]    = "Tuloilma-anturi",
    [TXT_FAULT_CO2_ALARM]        = "CO2-hälytys",
    [TXT_FAULT_OUTDOOR_SENSOR]   = "Ulkoilma-anturi",
    [TXT_FAULT_EXTRACT_SENSOR]   = "Poistoilma-anturi",
    [TXT_FAULT_WATER_COIL_FROST] = "Vesipatterin jäätymisvaara",
    [TXT_FAULT_EXHAUST_SENSOR]   = "Jäteilma-anturi",
    [TXT_FAULT_UNKNOWN]          = "Koodi %d",
};
