// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Miro Eilola / Mironet
//
// Pre-rendered bitmap fonts: Inter, three sizes, 4-bit alpha per pixel. Tables
// are generated by tools/fontgen.py and committed; nothing here rasterises.
#ifndef PANEL_FONT_H
#define PANEL_FONT_H
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint16_t cp;     // code point
    uint8_t  w, h;   // bitmap size in pixels (0×0 for space)
    int8_t   xoff;   // left bearing: first column is drawn at pen_x + xoff
    int8_t   yoff;   // rows above the baseline: row 0 is drawn at baseline - yoff
    uint8_t  adv;    // pen advance
    uint32_t off;    // byte offset of row 0 in font_t::bitmap; rows are (w+1)/2 bytes
} glyph_t;

typedef struct {
    uint8_t  px;        // nominal size
    uint8_t  ascent;    // baseline is ascent px below the top of a text line
    uint8_t  descent;
    uint8_t  line_h;    // ascent + descent (+ gap)
    uint16_t n;         // glyph count, sorted by cp
    const glyph_t *glyphs;
    const uint8_t *bitmap;   // 4-bit alpha, two pixels per byte, high nibble first
} font_t;

extern const font_t font_inter_12;
extern const font_t font_inter_18;
extern const font_t font_inter_36;

const glyph_t *font_find_glyph(const font_t *f, uint16_t cp);   // NULL when absent

// Decode one UTF-8 code point and advance *s. Returns 0 at the terminator.
// Code points above U+FFFF and malformed sequences decode as '?'.
uint16_t font_utf8_next(const char **s);

// Width in pixels of a UTF-8 string: the sum of advances; a code point without
// a glyph counts as '?'.
uint16_t font_text_width(const font_t *f, const char *utf8);

#ifdef __cplusplus
}
#endif
#endif
