#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Miro Eilola / Mironet
"""Render a TTF into C tables for panel_ui/font.h.

    python3 tools/fontgen.py <font.ttf> <px> [<px> ...] <outdir>

For each size writes <outdir>/font_<name>_<px>.c with a sorted glyph_t table and
a 4-bit alpha bitmap (two pixels per byte, high nibble first), for the glyph set
U+0020..U+007E plus ä ö å Ä Ö Å °. Requires Pillow (with FreeType).
"""
import hashlib
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

GLYPHS = list(range(0x20, 0x7F)) + [0xE4, 0xF6, 0xE5, 0xC4, 0xD6, 0xC5, 0xB0]


def render(ttf: Path, px: int):
    font = ImageFont.truetype(str(ttf), px)
    ascent, descent = font.getmetrics()
    glyphs, bitmap = [], bytearray()
    for cp in GLYPHS:
        ch = chr(cp)
        # bbox relative to the baseline-left anchor: (x0, y0, x1, y1), y grows down
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        adv = int(round(font.getlength(ch)))
        w, h = x1 - x0, y1 - y0
        if w <= 0 or h <= 0 or ch == " ":
            glyphs.append((cp, 0, 0, 0, 0, adv, len(bitmap)))
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
        # Pillow's getbbox spans the advance horizontally and down to the baseline
        # vertically; trim to the ink so bearings and sizes are tight.
        ink = img.getbbox()
        if ink is None:
            glyphs.append((cp, 0, 0, 0, 0, adv, len(bitmap)))
            continue
        img = img.crop(ink)
        x0, y0 = x0 + ink[0], y0 + ink[1]
        w, h = img.size
        px_data = img.tobytes()
        off = len(bitmap)
        stride = (w + 1) // 2
        for r in range(h):
            row = bytearray(stride)
            for c in range(w):
                a = px_data[r * w + c] >> 4          # 8-bit → 4-bit alpha
                if c % 2 == 0:
                    row[c // 2] |= a << 4
                else:
                    row[c // 2] |= a
            bitmap += row
        # yoff = rows above the baseline: y0 is negative above the baseline
        glyphs.append((cp, w, h, x0, -y0, adv, off))
    glyphs.sort(key=lambda g: g[0])
    return ascent, descent, glyphs, bytes(bitmap)


def emit(out: Path, name: str, px: int, ttf: Path, ascent, descent, glyphs, bitmap):
    sha = hashlib.sha256(ttf.read_bytes()).hexdigest()[:16]
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// SPDX-FileCopyrightText: 2026 Miro Eilola / Mironet",
        f"// Generated by tools/fontgen.py from {ttf.name} (sha256 {sha}…) at {px} px — do not edit.",
        '#include "font.h"',
        "",
        f"static const uint8_t k_bitmap_{px}[] = {{",
    ]
    for i in range(0, len(bitmap), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 16]) + ",")
    if not bitmap:
        lines.append("    0,")
    lines.append("};")
    lines.append("")
    lines.append(f"static const glyph_t k_glyphs_{px}[] = {{")
    for cp, w, h, xoff, yoff, adv, off in glyphs:
        lines.append(f"    {{ 0x{cp:04X}, {w}, {h}, {xoff}, {yoff}, {adv}, {off}u }},")
    lines.append("};")
    lines.append("")
    lines.append(
        f"const font_t font_{name}_{px} = {{ {px}, {ascent}, {descent}, {ascent + descent}, "
        f"{len(glyphs)}, k_glyphs_{px}, k_bitmap_{px} }};"
    )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv):
    if len(argv) < 4:
        print(__doc__)
        return 2
    ttf = Path(argv[1])
    outdir = Path(argv[-1])
    sizes = [int(a) for a in argv[2:-1]]
    name = ttf.stem.split("-")[0].lower()          # Inter-Regular.ttf → inter
    outdir.mkdir(parents=True, exist_ok=True)
    for px in sizes:
        ascent, descent, glyphs, bitmap = render(ttf, px)
        emit(outdir / f"font_{name}_{px}.c", name, px, ttf, ascent, descent, glyphs, bitmap)
        print(f"{px} px: {len(glyphs)} glyphs, {len(bitmap)} bytes bitmap, ascent {ascent} descent {descent}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
